sudo: false
language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
env:
    matrix:
        - ODDT_TOOLKIT=ob
        - ODDT_TOOLKIT=rdk
    global:
        secure: OVE5GtJJ2Ga+GDJIFuyPsbJ5SFCecdbiPv6TzrdNT6AoMdjEZK/zw1ZRHNtMHvrPbq5G7qY/54tHEePSKJlm7pi8agYPbTAg3pPvUvFfmyoQm4Vg07BEULKJ9wfgNI2c+IsMp77r1hW+04+HpwMT81p/zYndVcuhvj7C7vJ0hgo=
deploy:

    # pypi
    - provider: pypi
      user: mwojcikowski
      password:
          secure: Y1+kPOAjQhFZW9N25q8StT5TFvJiUhecTbmpHIlGzlPi/L/RUE8txXXI5e7o4lD0bz5pqDtoKwF8Nas2VQJGS/dE0lkjmsDR/cQdjoSd88BflhxaqlvL6L2fVmIZ2RWXXmrlE6s/Obw1JpMjtzhCGk0ywe306Z1NVkj1VEURIlc=
      distributions: sdist bdist_wheel egg_info
      on:
          tags: true
          repo: oddt/oddt
          branch: master
    # conda
    - provider: script
      script: conda/deploy.sh
      on:
          tags: true
          repo: oddt/oddt
          branch: master
      skip_cleanup: true
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
         wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
         wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -q conda-build anaconda-client
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose numpydoc six scipy numpy scipy scikit-learn joblib pandas coverage pillow
    - source activate test-environment
    - conda install -q -c mwojcikowski openbabel
    - conda install -q -c rdkit rdkit
    - pip install coveralls
    - python setup.py install
script:
    - nosetests --with-coverage --cover-package oddt
    - oddt_cli --help
    - oddt_cli tests/data/dude/xiap/crystal_ligand.sdf -osmi
after_success:
    - coveralls
